### [Physics queries](Physics%20Queries.md)
- [LayerMasks](Physics%20Queries/Layer%20Masks.md)
- [GameObject layers](Physics%20Queries/GameObject%20Layers.md)
- [Ignore Raycast](Physics%20Queries/Ignore%20Raycast.md)
- Incorrect parameters [3D](Physics%20Queries/Incorrect%20Parameters%203D.md) or [2D](Physics%20Queries/Incorrect%20Parameters%202D.md)
- General issues [3D](Physics%20Queries/Physics%20Queries%203D.md) or [2D](Physics%20Queries/Physics%20Queries%202D.md)
- NonAlloc [3D](Physics%20Queries/NonAlloc%203D.md) or [2D](Physics%20Queries/NonAlloc%202D.md)
- [Visual debugging](Physics%20Queries/Visual%20Debugging.md)
