### [Script loading issues](Loading%20Issues.md)
- [Class and file names](Loading%20Issues/Script%20Name.md)
- [Console errors](Loading%20Issues/Console%20Errors.md)
- [Checking inheritance](Loading%20Issues/Base%20Type.md)
- [Editor contexts](Loading%20Issues/Editor%20Contexts.md)
   - [Editor folders](Loading%20Issues/Editor%20Folders.md)
   - [Editor Assembly Definitions](Loading%20Issues/Assembly%20Definitions.md)
- [Restart Unity](Loading%20Issues/Restart%20Unity.md)
- [Project reimport](Loading%20Issues/Project%20Reimport.md)